name: Structr CI Pipeline
on:
  push

jobs:
  run-tests:
    if: ${{ !startsWith( github.actor, 'dependabot' ) }}
    runs-on: self-hosted
    environment: build-and-test
    strategy:
      matrix:
        neo4jVersion: [3.5, 4.4, 5]
        module: [structr-base, structr-ui, structr-core, structr-rest, structr-db-driver-api, structr-memgraph-driver, structr-memory-driver, structr-modules, structr-neo4j-bolt-driver]
        include:
          - neo4jVersion: 3.5
            neo4jVersionVariable: 3_5
          - neo4jVersion: 4.4
            neo4jVersionVariable: 4_4
          - neo4jVersion: 5
            neo4jVersionVariable: 5
          - module: structr-base
            structrModuleVariable: BASE
          - module: structr-ui
            structrModuleVariable: UI
          - module: structr-core
            structrModuleVariable: CORE
          - module: structr-rest
            structrModuleVariable: REST
          - module: structr-db-driver-api
            structrModuleVariable: DB_DRIVER_API
          - module: structr-memgraph-driver
            structrModuleVariable: MEMGRAPH_DRIVER
          - module: structr-memory-driver
            structrModuleVariable: MEMORY_DRIVER
          - module: structr-modules
            structrModuleVariable: MODULES
          - module: structr-neo4j-bolt-driver
            structrModuleVariable: NEO4J_BOLT_DRIVER

    steps:
      - uses: actions/checkout@v3

      - name: Start Test Database
        run: >-
          docker run -d --name ${{ matrix.module }}-neo4j_${{ matrix.neo4jVersion }}-test-${{ github.run_id }} 
          -p 7687 
          -e NEO4J_AUTH=neo4j/admin 
          -e NEO4J_ACCEPT_LICENSE_AGREEMENT=yes 
          -e NEO4J_dbms_memory_heap_maxSize=4G 
          -e NEO4J_dbms_memory_pagecache_size=4G neo4j:${{ matrix.neo4jVersion }} && 
          echo "ASSIGNED_PORT_${{ matrix.structrModuleVariable }}_${{ matrix.neo4jVersionVariable }}_${{ github.run_id }}=$(docker inspect --format='{{(index (index .NetworkSettings.Ports "7687/tcp") 0).HostPort}}' ${{ matrix.module }}-neo4j_${{ matrix.neo4jVersion }}-test-${{ github.run_id }})" >> $GITHUB_ENV

      - name: Install GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          version: '22.2.0'
          java-version: '11'
          components: 'js,python'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Compile and run Tests
        run:  >-
          mvn clean install -DskipTests -DskipDist -DskipDocker -DskipDeb -DskipDockerTestDB && 
          cd ${{ matrix.module }} && 
          mvn install -DskipDockerTestDB -Denv.testDatabaseConnection="bolt://localhost:${ASSIGNED_PORT_${{ matrix.structrModuleVariable }}_${{ matrix.neo4jVersionVariable }}_${{ github.run_id }}}"

      - name: Stop Test Database
        if: always()
        run:  docker stop ${{ matrix.module }}-${{ matrix.neo4jVersionVariable }}-test-${{ github.run_id }}

  build-and-deploy:
    runs-on: self-hosted
    environment: build-and-test
    if: ${{ success() && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/release') }}
    needs: run-tests

    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: structr
          password: ${{ secrets.STRUCTR_DOCKER_PASSWORD }}

      - name: Install GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          version: '22.2.0'
          java-version: '11'
          components: 'js,python'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - run: mvn -U clean install -Pwith-sources -DskipTests -DskipDockerTestDB
      - name: Upload binaries
        run: >-
          scp -v structr-binaries/target/structr-*.deb structr.com:/files/repositories/upload > /dev/null 2>&1 &&
          scp -v structr-binaries/target/structr-*-dist.zip structr.com:/files/repositories/upload >/dev/null 2>&1

  cleanup-system:
    runs-on: self-hosted
    if: always()
    needs: [run-tests, build-and-deploy]
    steps:
      - name: Cleanup docker
        run: docker container prune -f && docker image prune -f && docker volume prune -f
      - name: Cleanup runner home
        run: cd ~/actions-runner/_work/structr/ && rm -rf structr
